### ISSUE TITLE
UTF-8 codes in WindowName

### ISSUE THREAD

**Issue by SergeyGhoru** [gggfreak2003/PyHook3#1]
PyHook3 can't decode UTF-8 codes like '\u2014' in WindowName (Windows 10).
Event click on window title "Untitled - Notepad" ("-" in title is character '\u2014'):

MessageName: mouse left down
Message: 513
Time: 21588265
Window: 9767612
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\PyHook3\HookManager.py", line 325, in MouseSwitch
    return func(event)
  File "C:\Python35\QT5\autopy2.py", line 19, in OnMouseEvent
    print('WindowName:',event.WindowName)
  File "C:\Python35\lib\encodings\cp866.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2014' in position 11: character maps to <undefined>

**Comment by gggfreak2003** [comment]
Sorry, I couldn't reproduce the error on my system. Could you please post some more details about your settings and some information about your system.
